### ISSUE TITLE
How can I get all the records the server had sent for a subscription?

### ISSUE THREAD

**Issue by dandv** [meteorhacks/subs-manager#11]
As we know, despite this being a very common scenario, [Meteor doesn't support querying against a publication](https://groups.google.com/forum/#!topic/meteor-core/m685gtqGi5I), in other words finding on the clients all the records that a particular subscription has returned.

I have a large collection on the server called `content`, and different filters against it on the server (e.g. content of various types, search fields etc.), with differently named pub/sub for each: `content` for the most recent items, `content-portfolio` for content that matches a company in the user's portfolio. Without **subs-manager**, when the route changes from one view to another, the server resets the publication and I can simply find on the client all the records that the server has published for that view by running 

    Content.find({})

However, after adding subs-manager, the *entire `Content` collection* apparently gets cached on the client, not just the subscription, and Content.find({}) in the `contentPortfolio` route returns the most recent items as well from the `content` subscription.

I only use subs-manager for the `content` subscription, and a regular `this.subscribe('content-portfolio')` for the portfolio-filtered subscription.

Since subs-manager manages subscriptions at a very low level, it would be great if there were a mechanism to isolate records coming from a specific subscription. That would be a super useful feature and it would solve [a very real problem](https://groups.google.com/d/msg/meteor-core/1Zpt46ndzgM/v6pAUr8BX6YJ) with Meteor core.

**Comment by arunoda** [comment]
I think we all good here.
