### ISSUE TITLE
Random extremely slow Mongo queries

### ISSUE THREAD

**Issue by dandv** [meteorhacks/subs-manager#14]
After using subs-manager for about a week, we've noticed extremely slow queries in the Mongo profiler (> 20 seconds). 

    db.system.profile.find({ }).limit(5).sort( { millis : -1 } )

These were generated by the Meteor app, and running a particular query again from the shell was fast. It was very hard to debug what was causing the problem, as subs-manager never was a suspect. However, removing subs-manager sped up the app by a lot, and now the slowest query takes only 2 seconds.

Unfortunately I used an expiring pastebin for the slow queries and I no longer have them, but I do remember that some were for empty selectors.

Would it be possible that subs-manager significantly slows down Mongo?

**Comment by arunoda** [comment]
It's hard to find a relationship with subs-manager.
