### ISSUE TITLE
Subscriptions that loads different fields of the same collection

### ISSUE THREAD

**Issue by Cerealkillerway** [meteorhacks/subs-manager#25]
I have a itemList route and a item/:name route; the first one shows a list of items, the other one, for every item shows the detailed information about it;

since the itemList route only needs the name of the item, it subscribes a publication that returns only that list (return Items.find({},{fields: {name: 1}}),
otherwise  the item/:name route needs all the fields for the current item, so it subscribes a publication that returns: Items.find({name: name},{limit: 1})

loading the itemList route (that is ok) and then clicking on one item's name to navigate the item/:name route, doesn't work, since additional fields are not loaded; it seems that local Items collection is not updated with additional fields sended by the new subscription once they are already loaded by another subscription; in fact, pressing F5 on  the item/:name route, let everything work ok

**Comment by MaximDubrovin** [comment]
@Cerealkillerway, I'm not sure I completely understand your problem, but may be this helps https://medium.com/@MaxDubrovin/workaround-for-meteor-limitations-if-you-want-to-sub-for-more-nested-fields-of-already-received-docs-eb3fdbfe4e07

**Comment by Cerealkillerway** [comment]
Yes, that's a clear explanation about the problem I'm having; and a working solution; I also understand that this is not an issue related to subs-manager, but it's related to meteor's DDP protocol itself;  thanks for the tip

**Comment by arunoda** [comment]
So, we can close this issue right :)

**Comment by Cerealkillerway** [comment]
Right
