### ISSUE TITLE
Subscription keep all data, not only the ones related to the subscription.

### ISSUE THREAD

**Issue by tomitrescak** [meteorhacks/subs-manager#26]
I have app with a following route in iron-router:
/records/:recordId
with subscription setup up to return a record from a collection with a given id

When I navigate to the page `/records/1`, I have record with Id=1 available
Then, when I navigate to page `/records/2` I have TWO records on client, the one with Id=1 and the one with Id=2. Is this a bug in the subscription manager, is it somehow bug in my application or is it a feature of the subscription manager?

When I use standard Meteor subscription, on a given route I have only one record available, while with subscription manager, these records stack up.

**Comment by arunoda** [comment]
No. It's not an issue.
That's how subs manager works.

You need query with correct id to get the data.

I hope you are doing something like this.
~~~js
Records.find();
~~~

But now you need to do:
~~~js
var id = Router.current().params._id;
Records.find({_id: id});
~~~

Hope this helps.

**Comment by tomitrescak** [comment]
Yes, I'm doing that. All good, just making sure if it is a correct behaviour. Loving the performance gain!

**Comment by arunoda** [comment]
great.
