### ISSUE TITLE
Caching persists across refreshes?

### ISSUE THREAD

**Issue by SachaG** [meteorhacks/subs-manager#34]
If subs-manager caches some subscription data and I close and reopen a browser tab, does the data persist in local storage from one session to the next?

I just ran into a weird situation where data was available on the client even though I wasn't publishing it, and I was wondering if it could be because of subs-manager.

**Comment by SachaG** [comment]
Also, I somehow manage to make Telescope completely unusable in Chrome, it doesn't load at all. Works fine in incognito mode though, so I think somehow the subscription data got corrupted and is driving Iron Router in an infinite loop.

**Comment by arunoda** [comment]
Subsmanager never touch local storage. Not sure about the issue. Anyway
fast render might be the issue. Check that.

**Comment by SachaG** [comment]
OK, that was my other suspicion. I have to say that between IR, FastRender, and SubsManager I'm not sure who's doing what anymore…

**Comment by arunoda** [comment]
Actually, fast render also not righted to IR anymore. But that's a possible
place since we have placed some hacks into that.
