### ISSUE TITLE
Support for template subscriptions?

### ISSUE THREAD

**Issue by dcworldwide** [meteorhacks/subs-manager#36]
WIll this work as a like for like replacement for template subscriptions? If i use this.subscribe within my template create(), will Template.subscriptionReady api will work as expected? Thanks

**Comment by txs** [comment]
Yeah this will be an interesting problem to solve

**Comment by voidale** [comment]
+1

**Comment by maxnowack** [comment]
+1

**Comment by fpoirier1** [comment]
+1

**Comment by jimmiebtlr** [comment]
There seems to be several possible routes on the implementation of this.

* Basically hijack the unsubscribe during template destruction, and have subs-manager take over at that point.  There would need to be a way to add an existing subscription into subs-manager, without completely re-subscribing.
* Start the expire in timer when unsubscribe is called, by replacing `this.subscribe` with a subs-manager method.

It seems like with one of those two features, hooking into blaze template scope subscriptions should be fairly trivial.

**Comment by wI2L** [comment]
+1

**Comment by wI2L** [comment]
@arunoda Are you planning to add this feature to subs-manager ? It would be very usefull. I recently watched your screencast about DOM/Template caching, and i think the packages combined could be very powerfull to speed up a Meteor app.

**Comment by arunoda** [comment]
Nope. SubsManager won't be directly supporting Template subs. But, there can be another project which adds that support.

When we are doing Template caching, we don't need to cache subscriptions.

**Comment by wI2L** [comment]
@arunoda Okay, thank you for the answer. Can't wait for you new package then :smile:

**Comment by funkyeah** [comment]
@arunoda what do you use to do Template caching or how do you implement that?

@wI2L I think you may have mis-understood arunoda, I think he is saying you could make a different package (maybe fork this one) and add support for Template subs, but I don't think he is saying that he is working on a new package

**Comment by arunoda** [comment]
We use FlowComponents with Blaze and their we've implemented our own component level caching system our own. There we used subs-manager. 

Here we don't need to fork subs-manager. Another project which overrides template level subs and use Subsmanager instead. 

With React this works pretty well by default. I assume in the future Meteor will kill Blaze or user stop using it. (May be use jsx templates).

@SachaG has a good way to doing it just using subs-manager and I like it. See: http://www.telescopeapp.org/blog/telescope-weekly-2-subs-manager-fast-render/ (at the end)
(@SachaG may be you can link the code here as well)

**Comment by SachaG** [comment]
Sure: https://github.com/TelescopeJS/Telescope/blob/devel/packages/telescope-posts/lib/client/templates/posts_list/posts_list_controller.js#L21-L22

**Comment by arunoda** [comment]
Great thanks.

**Comment by funkyeah** [comment]
Yes, thanks guys.

**Comment by wI2L** [comment]
@funkyeah No it was clear for me. I was speaking of his future package to cache the DOM between rendered views.

**Comment by funkyeah** [comment]
@wI2L ah, my bad... off to watch the screencast
