### ISSUE TITLE
Subscriptions don't expire anymore

### ISSUE THREAD

**Issue by webyak** [meteorhacks/subs-manager#38]
Subscriptions don't expire anymore. No unsub messages appear after the expired time (Note: I don't subscribe to them again). I as well tried it manually in the console with `expireIn` set to 1 minute.

Though it works when I clear the subs manager instance manually.

**Comment by arunoda** [comment]
SubsManager start cleaning subscriptions when changing the route. We do it purposely. We don't need to expire subs used in the current present.

I checked now, it works pretty well.

**Comment by webyak** [comment]
Oh, so when you switched from the route where the subscription got initiated to another route and wait there until it expires, you going to have a hard time waiting 😬

Thanks Arunoda!
