### ISSUE TITLE
SubsManager.subscribe  doesnt work if params contains special charaters

### ISSUE THREAD

**Issue by pahans** [meteorhacks/subs-manager#53]
I have something like this in my code 
`subMan.subscribe("subName", param);`
subscription doesn't work if `param` variable contain a string with special chars. (example string: "Method not found [404]")

when I replace subscription with Meteor.subscribe everything works as expected.

**Comment by arunoda** [comment]
So, here special char is "["?

**Comment by pahans** [comment]
the issue seems to be working now. i didnt do any changes. I ll close this for now and reopen if occurred again
